### ISSUE TITLE
[BUG] openjdk?

### ISSUE THREAD

**Issue by Charles2333** [gushmazuko/metasploit_in_termux#175] opened 2022-08-15 09:46 UTC
No command msfconsole found, did you mean:
Command bconsole in package bacula-fd
Command jconsole in package openjdk-17

**Comment by krisdowis** [comment] 2022-08-15 13:16
This issue is a duplicate of #163 
But you can solve the bug by using the command below

This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with this command for now
 ```
source <(curl -fsSL https://bit.ly/3cTWx5g)
```

Please note this is to fix the error for now I will remove/disable the link once owner approves pull request or fixes error

Please let me know if you were able to fix the problem or if you still have errors

**Comment by gushmazuko** [comment] 2022-08-16 21:25
Fixed thanks to @krisdowis

**Closed** 2022-08-16 21:28 UTC
Labels: resolved

**Comment by Mateusp2p** [comment] 2022-09-21 19:16
Amigo me ajudou muito parabéns

**Comment by krisdowis** [comment] 2022-09-25 06:21
> Amigo me ajudou muito parabéns

Você é bem vindo

**Comment by Charles2333** [comment] 2022-11-15 11:43
> This issue is a duplicate of #163 But you can solve the bug by using the command below
> 
> This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with this command for now
> 
> ```
> source <(curl -fsSL https://bit.ly/3cTWx5g)
> ```
> 
> Please note this is to fix the error for now I will remove/disable the link once owner approves pull request or fixes error
> 
> Please let me know if you were able to fix the problem or if you still have errors

Thank you for solving this problem, very useful.

**Comment by Alantantofaz** [comment] 2023-01-10 17:49
Tks

**Comment by Alantantofaz** [comment] 2023-01-10 17:50
Thank you

**Comment by Uhitn** [comment] 2023-02-16 04:37
Could not locate gem file 
![Uploading Screenshot_2023-02-16-11-07-14-297_com.termux.jpg…]()

**Comment by dedshit** [comment] 2023-02-16 08:04
@Uhitn please send a proper screenshot of the error that you having experiencing

**Comment by Shwoqj2eishvaob** [comment] 2023-02-18 23:40
> این مشکل تکراری از [شماره 163](https://github.com/gushmazuko/metasploit_in_termux/issues/163) است اما با استفاده از دستور زیر می توانید باگ را حل کنید
> 
> این اشتباه من بود، هنگام مشارکت در کد، خطایی مرتکب شدم، اما قبلاً یک درخواست کشش برای رفع آن باز کرده‌ام. مالک هنوز تأیید نکرده است زیرا مشغول است، اما فعلاً می‌توانید با این دستور آن را برطرف کنید.
> 
> ```
> source <(curl -fsSL https://bit.ly/3cTWx5g)
> ```
> 
> لطفاً توجه داشته باشید که این برای رفع خطا در حال حاضر است، پس از تأیید مالک درخواست کشش یا رفع خطا، پیوند را حذف/غیرفعال خواهم کرد
> 
> لطفاً به من اطلاع دهید که آیا توانستید مشکل را برطرف کنید یا اگر هنوز خطا دارید

The problem was not solved and it says the same thing again

**Comment by krisdowis** [comment] 2023-07-07 06:46
This is for openjdk not gemfile
