### ISSUE TITLE
Error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by N17R0-HACKERS** [gushmazuko/metasploit_in_termux#145] opened 2022-05-17 18:20 UTC
![IMG_20220517_234835](https://user-images.githubusercontent.com/72617624/168883286-bff2ef37-c7c2-473e-ad53-de98c3c7cba5.jpg)

**Comment by gushmazuko** [comment] 2022-05-17 18:47
Do you have a latest build? Or try another apk.

I tried to reproduce now and it works for me.

**Comment by N17R0-HACKERS** [comment] 2022-05-17 20:01
I Don't know about latest build.
Can you suggest me suggest apk builder.

Please.

**Comment by N17R0-HACKERS** [comment] 2022-05-17 21:28
now that error will changed.
==> Error: wrong number of arguments (given 3, expected 2)

**Comment by dedshit** [comment] 2022-05-18 10:46
> now that error will changed. ==> Error: wrong number of arguments (given 3, expected 2)



> ![IMG_20220517_234835](https://user-images.githubusercontent.com/72617624/168883286-bff2ef37-c7c2-473e-ad53-de98c3c7cba5.jpg)

is your apk encrypted ?

**Comment by N17R0-HACKERS** [comment] 2022-05-18 14:15
Idk

**Comment by aditya936** [comment] 2022-05-18 18:42
same error found .

undefined method `strip' for nil:NilClass (NoMethodError)

![IMG_20220519_000849](https://user-images.githubusercontent.com/87860972/169121489-810d2458-e020-4783-bf50-749d6713c48c.jpg)

**Comment by aditya936** [comment] 2022-05-18 18:45
same error found .

undefined method `strip' for nil:NilClass (NoMethodError)


![IMG_20220519_001445](https://user-images.githubusercontent.com/87860972/169122519-bebfe715-be91-4d1b-8432-e1246d998834.jpg)

**Comment by dedshit** [comment] 2022-05-19 03:09
> Idk 

send your apk as zip here let us check

**Comment by aditya936** [comment] 2022-05-20 13:45
Here the app link 
https://m.apkpure.com/internet-speed-meter-lite/com.internet.speed.meter.lite

**Comment by dedshit** [comment] 2022-05-20 17:15
> Here the app link https://m.apkpure.com/internet-speed-meter-lite/com.internet.speed.meter.lite

![Screenshot_20220520-224347_Termux](https://user-images.githubusercontent.com/62318734/169579215-5707abbf-c6be-465f-9a01-b35fae07d473.png)

**Comment by N17R0-HACKERS** [comment] 2022-05-21 01:16
> > now that error will changed. ==> Error: wrong number of arguments (given 3, expected 2)
> 
> > ![IMG_20220517_234835](https://user-images.githubusercontent.com/72617624/168883286-bff2ef37-c7c2-473e-ad53-de98c3c7cba5.jpg)
> 
> is your apk encrypted ? if not share your apk link or in zip .

My apk is not encrypted 
And I am trying other apps also but 
His showing same error 
Error: wrong number of arguments (given 3, expected 2)

**Comment by dedshit** [comment] 2022-05-21 02:29
> > > now that error will changed. ==> Error: wrong number of arguments (given 3, expected 2)
> > 
> > > ![IMG_20220517_234835](https://user-images.githubusercontent.com/72617624/168883286-bff2ef37-c7c2-473e-ad53-de98c3c7cba5.jpg)
> > 
> > is your apk encrypted ? if not share your apk link or in zip .
> 
> My apk is not encrypted 
> And I am trying other apps also but 
> His showing same error 
> Error: wrong number of arguments (given 3, expected 2)
> 
> 

send those apk links

**Comment by dedshit** [comment] 2022-05-21 06:30
> > > now that error will changed. ==> Error: wrong number of arguments (given 3, expected 2)
> > 
> > > ![IMG_20220517_234835](https://user-images.githubusercontent.com/72617624/168883286-bff2ef37-c7c2-473e-ad53-de98c3c7cba5.jpg)
> > 
> > is your apk encrypted ? if not share your apk link or in zip .
> 
> My apk is not encrypted 
> And I am trying other apps also but 
> His showing same error 
> Error: wrong number of arguments (given 3, expected 2)
> 
> 

are you sure about that your apk is not encrypted ?

**Comment by N17R0-HACKERS** [comment] 2022-05-21 19:24
Yes

**Comment by dedshit** [comment] 2022-05-22 02:18
> Yes

just send that apk link or close this issue

**Comment by aditya936** [comment] 2022-05-26 11:40
> > 
thank u❤️

**Comment by aditya936** [comment] 2022-05-26 11:44
![IMG_20220526_165249](https://user-images.githubusercontent.com/87860972/170481168-d1f9aa37-8e6c-4116-a4ec-81843cd5e29e.jpg)


any solution for this?  anyone
(i already search for this ...)

**Comment by dedshit** [comment] 2022-05-26 14:52
> ![IMG_20220526_165249](https://user-images.githubusercontent.com/87860972/170481168-d1f9aa37-8e6c-4116-a4ec-81843cd5e29e.jpg)
> 
> 
> any solution for this?  anyone
> (i already search for this ...)


ignore that warning sign. you need to patch.
hint : public.xml

**Comment by dedshit** [comment] 2022-05-26 16:46
> ![IMG_20220526_165249](https://user-images.githubusercontent.com/87860972/170481168-d1f9aa37-8e6c-4116-a4ec-81843cd5e29e.jpg)
> 
> 
> any solution for this?  anyone
> (i already search for this ...)

if you need to remove that [check this out](https://github.com/dedshit/Apk-Modding-challenge)

**Closed** 2022-08-16 21:30 UTC
